### ISSUE TITLE
Timeout (45 minutes) reached. Terminating "make docker_build"

### ISSUE THREAD

**Issue by zfrenchee** [bgruening/galaxy-flavor-testing#2]
Changed it locally to 300, which is a big upper bound. Will Travis do this for me?

**Comment by bgruening** [comment]
:-( its usually due to compiling dependencies. Conda is the solution here but takes time and effort.

**Comment by zfrenchee** [comment]
This isn't useful for most galaxy flavors I don't think -- because most flavors install tools and most tools take a very long time to install, right?

**Comment by bgruening** [comment]
I have migrated most tools in my flavors to conda already. Conda is the future, no compilation anymore. I bet most of your tools are already conda ready.

**Comment by zfrenchee** [comment]
How do I use conda tools instead of the current ones? [These are my tools](https://github.com/fraenkel-lab/galaxy-neurolincs/blob/master/tools.yml)

**Comment by bgruening** [comment]
Have a look at: https://github.com/bgruening/docker-galaxy-ngs-preprocessing/blob/master/ngs_preprocessing.yml#L55

But make sure your tools are available as bioconda package.

**Comment by zfrenchee** [comment]
So in order to use a conda package, you need to use conda, you just write:
```
  install_resolver_dependencies: True
  install_tool_dependencies: False
```
Is that correct?

**Comment by bgruening** [comment]
Yes you activate resolvers and deactivate tool_dependencies.

**Comment by zfrenchee** [comment]
Is there a page somewhere with a list of all the packages that have been conda-fied?

**Comment by bgruening** [comment]
No, but all packages that are not on the .tt_blacklist in tools-iuc, devteam, galaxytools ...

**Comment by zfrenchee** [comment]
- What is the tt_blacklist?
